name: CI-CD-Pallet-Detection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: âœ¨ Checkout Code
        uses: actions/checkout@v3

      - name: ğŸ“ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: â˜• Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: ğŸ›  Lint with flake8
        run: |
          flake8 src/ tests/

      - name: âœ… Run unit tests
        run: |
          pytest tests/

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: âœ¨ Checkout Code
        uses: actions/checkout@v3

      - name: âš–ï¸ Build Docker Image
        run: |
          docker build -t pallet-detector -f docker/Dockerfile .

      - name: ğŸšš Run Docker container
        run: |
          docker run -d -p 5000:5000 --name pallet-api pallet-detector
